production:
  host: dinesafe.to
  google_maps_browser_api_key: 
  app_store_link: # http://...
  app_store_id: # 9-digit app store ID

development:
  host: dinesafe.dev
  google_maps_browser_api_key: 
  app_store_link: # http://...
  app_store_id: # 9-digit app store ID

test: 
  host: 
  google_maps_browser_api_key: 
  app_store_link:
  app_store_id:
